Reacting with ct_semicolon to messages in introductions
nobobo1234/trainbot pull request #40
Opened 2020-09-02 14:23 UTC by arnavsirigere

2020-09-02 15:30 UTC, GypsyDangerous commented
so this would react to any message sent in introduction with ct_semicolon, which is waving.

2020-09-05 14:45 UTC, nobobo1234 requested changes
Here you go :)

2020-09-05 14:45 UTC, nobobo1234 commented on src/constants.js
> +    ct_semicolon: '664125053058678814',
Please adhere to the structure of the other emojis, with the name in the text.

2020-09-05 14:45 UTC, nobobo1234 commented on src/events/message.js
> +    }
I'd rather have this outsourced in the commands manager, make a separate class method e.g. `handleMessage` or `handleReactions` and call that from here, and before the Commands#handleCommand call.

2020-09-06 08:32 UTC, arnavsirigere commented
I think I fixed the stuff you told me to

2020-09-06 09:47 UTC, nobobo1234 requested changes

2020-09-06 09:47 UTC, nobobo1234 commented on src/managers/commands.js
> +            const [ctSemicolon] = emojis.ct_semicolon.match(/\d+/);
One small change I'd like to request for the sake of consistency, you don't have to get the id from the emoji itself, you are able to react with the full string that is present in the emoji.js file as I did [here](https://github.com/CodingTrain/trainbot/blob/master/src/commands/information/userinfo.js#L12-L15).

2020-09-06 09:47 UTC, nobobo1234 commented
All the other stuff looked great!

2020-09-06 10:15 UTC, arnavsirigere commented
Im pretty sure you get an error if you try to react with the full string. The react function expects only the id if im not wrong. Putting the full string does work in a message however

2020-09-06 10:18 UTC, nobobo1234 commented
You are absolutely right, I'll approve it :)

2020-09-06 10:19 UTC, nobobo1234 approved these changes

2020-09-06 10:20 UTC, nobobo1234 commented
@all-contributors please add @arnavsirigere for code

2020-09-06 10:21 UTC, nobobo1234 commented
@all-contributors please add @nobobo1234 for review

2020-09-06 10:21 UTC, merged

2020-09-21 14:38 UTC, arnavsirigere commented
I just realised this isnt working. Any idea why?

2020-09-21 14:44 UTC, nobobo1234 commented
I didn't look closely when I pulled my changes, should be working now!